apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fj-analytics-db
  namespace: fj-analytics
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fj-analytics-uploads
  namespace: fj-analytics
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
