apiVersion: v1
kind: Secret
metadata:
  name: fj-analytics-secrets
  namespace: fj-analytics
type: Opaque
stringData:
  JWT_SECRET: "CHANGE-THIS-TO-A-SECURE-32-CHAR-MIN-KEY"
  ADMIN_EMAIL: "admin@yourcompany.com"
  ADMIN_PASSWORD: "CHANGE-THIS-SECURE-PASSWORD"
